### ISSUE TITLE
Lower level boundaries

### ISSUE THREAD

**Issue by justinelliotmeyers** [jmgclark/tunisia_shapefiles#1]
hey! I just found this repo, thank you so much for sharing! Have you seen points or polygons for villages/ towns/ settlements anywhere in your journeys of Tunisia gis data?

Thanks!!!
Justin

**Comment by jmgclark** [comment]
Hey Justin -- glad it's helpful. No, haven't seen anything on villages towns or settlements. Best of luck hunting :)
Julia

**Comment by justinelliotmeyers** [comment]
Thanks!
